### ISSUE TITLE
Invalid node type id Error for "Configure AWS Credentials" action

### ISSUE THREAD

**Issue by bradleyjlevine** [actionforge/vscode-ext#28]
## Describe the bug or feature

When trying to load the "Configure AWS Credentials" action it has the following error.

![image](https://github.com/actionforge/vscode-ext/assets/23265733/3b380714-af12-4919-a170-aa3d598c2917)

## To reproduce a bug

1. Go to https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
2. Click on 'Use Latest'
3. Copy Install
4. Paste into VS Code
![image](https://github.com/actionforge/vscode-ext/assets/23265733/7c265e66-55a7-4216-a70d-e58539d42f4c)
5. Load Github Action
6. See Error
![image](https://github.com/actionforge/vscode-ext/assets/23265733/b7570947-3dea-4400-a3e1-26923868229a)

## Expected behavior

Loads the action

## GitHub Repo Link

- https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
- https://github.com/aws-actions/configure-aws-credentials

## Additional context

Not sure what the issue is but, this AWS action does work

https://github.com/marketplace/actions/aws-secrets-manager-github-action
https://github.com/aws-actions/aws-secretsmanager-get-secrets

**Comment by sebastianrath** [comment]
Thanks for reporting! I'm on it

**Comment by sebastianrath** [comment]
The reason for the error message are the quotes in the action name, resulting in an invalid YAML snippet.

```
- name: "Configure AWS Credentials" Action for GitHub Actions
  uses: aws-actions/configure-aws-credentials@v4.0.2
```

<img width="682" alt="Screenshot 2024-03-28 at 9 01 16 PM" src="https://github.com/actionforge/vscode-ext/assets/12844423/029b9a66-f11e-4ac0-92cd-e3d92099c15d">

Remove the quotes, and the action can be loaded succesfully.

```
- name: "Configure AWS Credentials"
  uses: aws-actions/configure-aws-credentials@v4.0.2
```

**Comment by bradleyjlevine** [comment]
Thank you!  That works for me.
